### ISSUE TITLE
[Feat] - 메인페이지 방 만들기 버튼 모달창 구현

### ISSUE THREAD

**Issue by seokachu** [TeamSparta-Project/ice-craft#40]
📕 Issue Feature 
방 만들기 버튼 모달 창 구현

🧾Todo
- [ ] 빠른입장 클릭시 마피아 게임 페이지로 이동하기
- [x] 방 만들기 버튼 클릭시 게임 선택 모달창 보이기
- [x] 모달 창 넘겨서 마피아 페이지 이동하기

**Comment by joo1e** [comment]
완료
1. 방만들기 클릭 시 방만들기 모달창 구현
2. 방만들기 데이터 기반으로 방 생성
